name: flutter_admin_template_frontend
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.3

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animated_tree_view: ^2.1.0
  calendar_date_picker2: ^0.3.5
  cupertino_icons: ^1.0.2
  d_chart: ^2.2.11
  dio: ^5.2.1+1
  dropdown_button2: ^1.9.2
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_smart_dialog: ^4.9.0+6
  hovering: ^1.0.4
  i18n_extension: ^9.0.0
  intl: 0.18.0
  just_the_tooltip: ^0.0.12
  loading_indicator: ^3.1.0
  shared_preferences: ^2.1.2
  sm_crypto: ^1.0.3
  super_context_menu: ^0.1.0
  web_socket_channel: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

deferred-components:
  - name: fat 
    libraries:
      - package:flutter_admin_template_frontend/signin/login_screen.dart
      - package:flutter_admin_template_frontend/dashboard/dashboard_screen.dart
      - package:flutter_admin_template_frontend/dept/dept_screen.dart
      - package:flutter_admin_template_frontend/menu/menu_screen.dart
      - package:flutter_admin_template_frontend/user/user_screen.dart
      - package:flutter_admin_template_frontend/log/log_summary_screen.dart
      - package:flutter_admin_template_frontend/log/sign_in_log_screen.dart
      - package:flutter_admin_template_frontend/log/operation_log_screen.dart
      - package:flutter_admin_template_frontend/role/role_screen.dart


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  
