title = "toml config file"

[database]
name = "flutter_admin_template"
address = "localhost"
port = "3306"
username = "root"
password = "123456"
database = "flutter_admin_template"

[redis]
hostname = "127.0.0.1"
port = "6379"

[middleware]
reject_times = 10
reject_duration = 10